from __future__ import annotations

from typing import Protocol, runtime_checkable

from tools.interfaces import ToolResult


@runtime_checkable
class GitOperations(Protocol):
    """Contract for all git operations used by the CTO."""

    def status(self, cwd: str) -> ToolResult: ...
    def diff(self, cwd: str, staged: bool = False) -> ToolResult: ...
    def log(self, cwd: str, n: int = 10) -> ToolResult: ...
    def add(self, cwd: str, paths: list[str]) -> ToolResult: ...
    def commit(self, cwd: str, message: str) -> ToolResult: ...
    def branch_list(self, cwd: str) -> ToolResult: ...
    def branch_create(self, cwd: str, name: str) -> ToolResult: ...
    def branch_delete(self, cwd: str, name: str) -> ToolResult: ...
    def checkout(self, cwd: str, target: str) -> ToolResult: ...
    def push(self, cwd: str, remote: str = "origin", branch: str = "HEAD") -> ToolResult: ...
    def pull(self, cwd: str, remote: str = "origin", branch: str = "HEAD") -> ToolResult: ...
    def reset_hard(self, cwd: str, target: str = "HEAD") -> ToolResult: ...
    def force_push(self, cwd: str, remote: str = "origin", branch: str = "HEAD") -> ToolResult: ...
